app:
  eureka:
    address: localhost
    port: 8010
server:
  port: 8020
spring:
  application:
    name: gateway
endpoints:
  shutdown:
    enabled: false
management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: false
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 60000
logging.level:
  '[com.zaxxer.hikari.pool.HikariPool]': INFO
  '[org.springframework]': INFO
  '[org.springframework.data.mongodb.repository.query]': INFO
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url.defaultZone: http://${app.eureka.address}:${app.eureka.port}/eureka
    healthcheck.enabled: true