server:
  port: 8010
spring:
  application:
    name: eureka
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    evictionIntervalTimerInMs: 2000
management:
  endpoint:
    shutdown:
      enabled: false
endpoints:
  shutdown:
    enabled: false

yc:
  app:
    name: ${spring.application.name}
    port: ${server.port}
