CREATE TABLE atendimento.atendimento (
    id BIGSERIAL PRIMARY KEY,
    prestador_id BIGINT NOT NULL,
    cliente_id BIGINT,
    cliente_nome VARCHAR(255),
    cliente_telefone_numero VARCHAR(15),
    cliente_telefone_tipo VARCHAR(15),
    cliente_whatsapp_numero VARCHAR(15),
    cliente_whatsapp_tipo VARCHAR(15),
    veiculo_id BIGINT,
    veiculo_placa VARCHAR(20),
    tipo_ocorrencia VARCHAR(255) NOT NULL,
    tipo_servico VARCHAR(255) NOT NULL,
    status VARCHAR(50) NOT NULL,
    data_hora_chamado TIMESTAMP NOT NULL,
    data_hora_confirmado TIMESTAMP,
    data_hora_em_andamento TIMESTAMP,
    data_hora_finalizado TIMESTAMP,
    data_hora_cancelado TIMESTAMP,
    descricao TEXT,
    endereco_base_rua VARCHAR(255),
    endereco_base_numero VARCHAR(10),
    endereco_base_complemento VARCHAR(255),
    endereco_base_bairro VARCHAR(255),
    endereco_base_cidade VARCHAR(255),
    endereco_base_estado VARCHAR(2),
    endereco_base_cep VARCHAR(10),
    endereco_origem_rua VARCHAR(255),
    endereco_origem_numero VARCHAR(10),
    endereco_origem_complemento VARCHAR(255),
    endereco_origem_bairro VARCHAR(255),
    endereco_origem_cidade VARCHAR(255),
    endereco_origem_estado VARCHAR(2),
    endereco_origem_cep VARCHAR(10),
    endereco_destino_rua VARCHAR(255),
    endereco_destino_numero VARCHAR(10),
    endereco_destino_complemento VARCHAR(255),
    endereco_destino_bairro VARCHAR(255),
    endereco_destino_cidade VARCHAR(255),
    endereco_destino_estado VARCHAR(2),
    endereco_destino_cep VARCHAR(10)
);